const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const w=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{runScripts:'outside-only',url:'https://test.local/'}).window,d=w.document;
let scroll=850,visited='';Object.defineProperty(w,'scrollY',{get:()=>scroll});w.scrollTo=({top})=>scroll=top;
w.matchMedia=()=>({matches:true});w.requestAnimationFrame=fn=>fn();w.HTMLElement.prototype.scrollIntoView=function(){visited=this.id;};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
w.eval(fs.readFileSync(root+'/catalogue.js','utf8')+'\n'+fs.readFileSync(root+'/script.js','utf8'));
const get=id=>d.getElementById(id),change=el=>el.dispatchEvent(new w.Event('change',{bubbles:true}));
get('catalogCollection').value='Mini Prints';change(get('catalogCollection'));
const card=d.querySelector('[data-choose-design="DTF-147"]').closest('.design-card'),trigger=card.querySelector('.design-art');
trigger.click();assert(get('designDialog').open);assert(d.documentElement.classList.contains('detail-open'));assert.equal(get('detailPlacement').value,'Poitrine / petit logo');
get('detailProduct').value='hoodie';change(get('detailProduct'));
d.querySelector('[name=detailColor][value=Blanc]').checked=true;change(d.querySelector('[name=detailColor][value=Blanc]'));
assert.equal(get('detailFrame').dataset.product,'hoodie');assert.equal(get('detailFrame').dataset.placement,'chest');assert.equal(get('detailFrame').style.getPropertyValue('--panel-offset'),'-100%');
assert(get('detailGarment').src.endsWith('hoodie-blank-front.webp'));assert(get('detailArtwork').src.endsWith('DTF-147.webp'));
for(let i=0;i<10;i++)get('detailZoomIn').click();assert.equal(get('detailZoom').value,'250');assert(get('detailZoomIn').disabled);assert.equal(get('detailCanvas').style.width,'250%');
d.querySelector('[data-detail-view=art]').click();assert(!get('designDialogImage').hidden);assert(get('detailTextile').hidden);assert.equal(get('detailZoom').value,'100');
get('closeDesignDialog').click();assert(!d.documentElement.classList.contains('detail-open'));assert.equal(scroll,850);assert.equal(d.activeElement,trigger);assert.equal(get('catalogCollection').value,'Mini Prints');assert.equal(get('catalogCount').textContent,'12 / 12 designs');assert(!get('productConfigurator').dataset.designId);
trigger.click();get('detailProduct').value='hoodie';change(get('detailProduct'));d.querySelector('[name=detailColor][value=Blanc]').checked=true;change(d.querySelector('[name=detailColor][value=Blanc]'));get('chooseDialogDesign').click();
assert.equal(get('productConfigurator').dataset.designId,'DTF-147');assert.equal(d.querySelector('[name=product]:checked').value,'hoodie');assert.equal(d.querySelector('[name=color]:checked').value,'Blanc');assert.equal(get('productPlacement').value,'Poitrine / petit logo');assert.equal(visited,'configurateur');assert(!d.documentElement.classList.contains('detail-open'));
const duo=d.querySelector('[data-choose-design="DTF-114"]').closest('.design-card').querySelector('.design-art');duo.click();get('detailPlacement').value='Devant';change(get('detailPlacement'));assert(get('detailArtwork').src.endsWith('DTF-114-FRONT.webp'));assert(!get('designDialogFront').hidden);get('detailPlacement').value='Dos';change(get('detailPlacement'));assert(get('detailArtwork').src.endsWith('DTF-114.webp'));get('chooseDialogDesign').click();assert.equal(get('productPlacement').value,'Devant + dos');
duo.click();get('detailProduct').value='tote';change(get('detailProduct'));get('detailPlacement').value='Verso';change(get('detailPlacement'));assert(get('detailArtwork').src.endsWith('DTF-114.webp'));get('chooseDialogDesign').click();assert.equal(get('productPlacement').value,'Verso');assert(get('primaryArtwork').src.endsWith('DTF-114.webp'));
get('catalogSearch').value='no-results';get('catalogSearch').dispatchEvent(new w.Event('input'));assert(!get('catalogEmpty').hidden);get('catalogReset').click();assert.equal(get('catalogCount').textContent,'12 / 158 designs');assert.equal(get('catalogCollection').value,'');assert(get('miniThemeField').hidden);
trigger.click();get('designDialog').close();assert(!d.documentElement.classList.contains('detail-open'));assert.equal(d.activeElement,trigger);
console.log('PASS: 158 designs retained; live textile/color/chest and paired views; zoom limits; isolated drafts; confirmed options transfer; modal close restores focus, scroll and filters; reset filters.');w.close();
